version: '3.8'

services:
  app:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt/live/srv567903.hstgr.cloud/fullchain.pem:/etc/nginx/certs/fullchain.pem
        - /etc/letsencrypt/live/srv567903.hstgr.cloud/privkey.pem:/etc/nginx/certs/privkey.pem
      depends_on:
        - app